### ISSUE TITLE
.env Missing ?

### ISSUE THREAD

**Issue by starkmatt** [Jac0xb/lighthouse#10]
Hiya!

I'm keen to have a test and play but upon building using 

```
 npm run programs:build
```

Your build script is failing on [#L10](https://github.com/Jac0xb/lighthouse/blob/main/configs/scripts/program/build.sh#L10)

```
cat: .github/.env: No such file or directory
```

I can see in your .gitignore the .env file is added[ #L13](https://github.com/Jac0xb/lighthouse/blob/main/.gitignore#L13)

Is this expected?

**Comment by Jac0xb** [comment]
See https://github.com/Jac0xb/lighthouse/pull/12 if you'd like to build the programs

I am refactor the codebase

**Comment by starkmatt** [comment]
Thank you looks great @Jac0xb 

Closing Issue :pray:
