### ISSUE TITLE
More assertions 

### ISSUE THREAD

**Issue by ohaddahan** [Jac0xb/lighthouse#16]
I built this tiny `program` a long time ago, I think you can add its content into `lighthouse`:
https://github.com/ohaddahan/solana-sandwich/tree/master

It can be used by `protocols` to ensure no one is trying to act malicious, for example reopening an `account` that the `program` closed, can be enforced by marking a `instruction` as nothing is allowed after, thus making it the end of the `transaction` and removing this potential issue.

**Comment by ohaddahan** [comment]
A bit more context @Jac0xb , `solana-sandwich` is more oriented to be used from inside a `solana-program` to ensure it's not being abused and it's valid only within one `transaction`.

Hence it's a slightly different approach and issues vs. the existing ones in `lightouse` which (I think) fits more for cross-transaction issues, such as `mev`.

**Comment by Jac0xb** [comment]
I appreciate this issue, I do however feel since instructions can be inspected before the transaction is signed and sent that this probably wouldn't be used by anyone.
